(define (square x) (* x x))
(define (sos a b) 
  (+ (square a) 
     (square b)))
(define (smallestTF a b c)
  (not (or (> a b) (> a c))))
(define (sosLarger2 a b c)
  (cond ((smallestTF a b c) (sos b c))
        ((smallestTF b a c) (sos a c))
        (else (sos a b))))